# DOES NOT WORK
merge when ready:
  - ./**/*

# DOES NOT WORK
configuration:
  - ./**/*.yml

# It works
html:
  - html/**/*.html

# It works
conf:
  - conf/**/*

# It works
github:
  - .github/**/*
